---
- hosts: localhost
  connection: local
  tasks:
  - name: "{{ item.name }}"
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "rishikp"
        #vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t3.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - { image: "ami-00ca32bbc84273381", name: "manage-node-1" }
      - { image: "ami-0360c520857e3138f", name: "manage-node-2" }
      - { image: "ami-0360c520857e3138f", name: "manage-node-3" }
