---
- name: launch EC2 instance
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    instance_type: "{{ type }}"
    security_group: default
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    tags:
      Environment: Testing

